export const environment = {
  production: true,
  wsURL: 'https://gablum-dev.stackroute.io/api/auctions/ws',
  alertURL: 'https://gablum-dev.stackroute.io/api/users/ws',
  loginApi: 'https://gablum-dev.stackroute.io/api/users/signin',
  logoutApi: 'https://gablum-dev.stackroute.io/api/users/signout',
  registerApi: 'https://gablum-dev.stackroute.io/api/users/signup',
  contractsUrl: 'https://gablum-dev.stackroute.io/api/contracts/contracts',
  profileUrl: 'https://gablum-dev.stackroute.io/api/users/profile',
  proposalUrl: 'https://gablum-dev.stackroute.io/api/proposals/proposals',
  guestProposallistUrl: 'https://gablum-dev.stackroute.io/api/proposals/proposals/browse',
  navlinkUrl: 'https://gablum-dev.stackroute.io/api/users/menuitems',
  auctionUrl: 'https://gablum-dev.stackroute.io/api/auctions/auctions',
  tokenUrl: 'https://gablum-dev.stackroute.io/api/auctions/tokens',
  inviteSellerUrl: 'https://gablum-dev.stackroute.io/api/proposals/proposals/invite',
  saveSellerViewUrl: 'https://gablum-dev.stackroute.io/api/proposals/proposals/views',
};
