spring:
  data:
    mongodb:
      uri: mongodb://db:27017/user
  mail:
    host: smtp.gmail.com
    port: 587
    username: gablumservices@gmail.com
    password: GaB1uMservices
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory