#server:
#  port: 8080
#
#spring:
#  application:
#    name: "scheduler-service"
#  data:
#    mongodb:
#      uri: mongodb://gablum:GaB1uM@localhost:27017
#      authentication-database: admin
#      database: scheduler